MainWidget:

<MainWidget>:
    canvas:
        Color:
            rgba: 1, .1, .1, .9
        Line:
            width: 2.
            ellipse: (self.x, self.y, self.width, self.height)

    Button:
        text: "+"
        size: "100dp", "40dp"
        pos: "350dp", "550dp"
        # call function from main file with button press
        on_press: root.addInt()

    Button:
        text: "+"
        size: "100dp", "40dp"
        pos: "350dp", "20dp"