FloatLayouts:


<FloatLayouts>:


    FloatLayout:
        orientation: "vertical"

        Image:
            source: "images/Room2p2.png"
            allow_stretch: True
            keep_ratio: False
            fit_mode: "contain"

        Button:
            text: "HATCH SPEED"
            size_hint: .50, .15
            pos_hint: {'left': 1, 'bottom': 1}

        Button:
            text: "2X HATCH"
            size_hint: .50, .15
            pos_hint: {'right': 1, 'bottom': 1}